fix

diff --git a/watch2 b/watch2
--- a/watch2
+++ b/watch2
@@ -33,6 +33,20 @@ if ! command -v vlc 2>/dev/null >/dev/null; then
 	return
 fi
 
+if ! command -v python3 2>/dev/null >/dev/null; then
+	echo "python3 not found. Cannot use watch2."
+	return
+fi
+
+if [[ ! -e $SCRIPT_DIR/.shellscript_functions ]]; then
+	echo "$SCRIPT_DIR/.shellscript_functions was not found"
+	exit 1
+fi
+
+if [[ ! -e $SCRIPT_DIR/.watch2.py ]]; then
+	echo "$SCRIPT_DIR/.watch2.py was not found"
+	exit 1
+fi
 
 source $SCRIPT_DIR/.shellscript_functions
 
